config/routes.rb
Yarora::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)

  root 'welcome#index'
  get 'features' => 'welcome#features', as: :features

  resource :user_profile, only: [:show, :update]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/profile.rb
module Profile
  def self.table_name_prefix
    'profile_'
  end
end

app/models/profile/address.rb
class Profile::Address < ActiveRecord::Base
  belongs_to :user_profile

  validates :postal_code, presence: true,
            allow_blank: true,
            format: { with: /\d/ },
            length: { is: 5 },
            on: :update
end

app/models/user.rb
#
# User model class that represents an account and is used and depended on by Devise
#
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile

  after_create :create_user_profile

  private

  def create_user_profile
    UserProfile.create_for_user(self)
  end
end

app/models/user_profile.rb
#
# The User Profile
#
class UserProfile < ActiveRecord::Base
  belongs_to :user
  has_one :profile_address, :class_name => 'Profile::Address'

  validates :name, presence: true

  accepts_nested_attributes_for :profile_address

  def self.create_for_user(_user)
    user_profile = create user: _user, name: _user.email
    Profile::Address.create user_profile: user_profile
    user_profile
  end
end

app/controllers/application_controller.rb
#
# Main Application Controller
#
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  #
  # Sets the locale, either by retrieving params[:local], setting/reading session[:locale]
  # or the default I18n.locale
  # @return nothing
  #
  def set_locale
    if params[:locale]
      I18n.locale = session[:locale] = params[:locale] || I18n.default_locale
    else
      I18n.locale = session[:locale] || I18n.default_locale
    end
  end
end

app/controllers/user_profiles_controller.rb
#
# User Profile Controller
#

class UserProfilesController < ApplicationController

  before_filter :get_user_profile

  # GET #show /user_profile
  def show
  end


  # PUT #update /user_profile
  def update
    if @user_profile.update(user_profile_params)
      flash.now[:notice] = I18n.t('update_success')
    else
      flash.now[:alert] = I18n.t('update_failure')
    end

    render :show
  end

  private

  def get_user_profile
    @user_profile = current_user.user_profile
  end

  def user_profile_params
    params.require(:user_profile).permit!
  end
end

app/controllers/welcome_controller.rb
#
# WelcomeController used as a landing for the Application
#
class WelcomeController < ApplicationController

  # before_action :authenticate_user!, only: [:features]

  #
  # GET features/ (features_path)
  # @return the feature page
  #
  def features
    redirect_to root_path, alert: 'Feature Disabled' if FeatureToggle.off?(:feature_page)
  end

  #
  # GET / (root_path)
  # @return the index page
  #
  def index
  end
end

app/helpers/application_helper.rb
# Some useful basic helper methods
module ApplicationHelper

  #
  # Displays the alternate locale icon of the already enabled locale
  # @return a link_to element for changing locale
  # TODO: Make me pass in view tests
  #
  def locale_switch
    _locale = I18n.locale
    _new_locale = case _locale
                    when :en
                      'de'
                    when :de
                      'en'
                    else

                  end

    link_to image_tag("#{_new_locale}.png"), url_for(locale: _new_locale)
  end

  #
  # Checks if given Feature is active by consulting the FeatureToggle module.
  #
  # @example
  #   feature_on?(:super_feature) # => true
  #
  # @param _feature [String] the feature to check
  # @return [Boolean] feature toggle's state
  #
  def feature_on?(_feature)
    FeatureToggle.on?(_feature)
  end

  #
  # Checks if given Feature is inactive by consulting the FeatureToggle module.
  #
  # @example
  #   feature_off?(:super_feature) # => false
  #
  # @param _feature [Symbol] feature to check
  # @return [Boolean] feature toggle's state
  #
  def feature_off?(_feature)
    FeatureToggle.off?(_feature)
  end

  def error_for_model_and_attribute(_model, _attribute)
    if _model.errors[_attribute].any?
      content_tag :div, class: 'error-label' do
        "(#{_model.errors[_attribute].join(', ')})"
      end
    end
  end
end

app/views/layouts/_footer.html.slim
footer
  .row.full.footy
    .large-12.columns
      .row
        .large-6.columns
          p
            small= '© Sebastian Georgi 2014'
        .large-6.columns
          ul.inline-list.right
            li
              small
                /a[href='http://sgeorgi.de']= 'Author'

app/views/layouts/_top_bar.html.slim
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      h1.show-for-medium-up
        =link_to t('header.title'), root_path
      h1.show-for-small-only
        =link_to t('header.shorttitle'), root_path
    li.toggle-topbar.menu-icon
      a href='#' = t('header.menu')

  section.top-bar-section
    ul.right
      - if feature_on?(:locale_switcher)
        li
          = locale_switch
      - if feature_on?(:user_login)
        li.divider
        - if not admin_user_signed_in?
          li.has-dropdown
            a href='#' = t('header.user.title')
            ul.dropdown
              - if not user_signed_in?
                li
                  =link_to t('header.user.login'), new_user_session_path
                li
                  =link_to t('header.user.signup'), new_user_registration_path
              - if user_signed_in?
                li
                  =link_to t('header.user.profile'), edit_user_registration_path
                - if feature_on?(:user_profile)
                  li
                    =link_to t('header.user.user_profile'), user_profile_path
                li
                  =link_to t('header.user.logout'), destroy_user_session_path, method: :delete
        - if not user_signed_in?
          li
            a href='/admin' = t('header.user.admin_title')
    ul.left
      li.divider
      li class="#{current_page?(root_path) ? 'active' : ''}"
        =link_to t('header.home'), root_path
      - if feature_on?(:feature_page)
        li class="#{current_page?(features_path) ? 'active' : ''}"
          =link_to t('header.features'), features_path

app/views/layouts/application.html.slim
doctype html
html ng-app="yarora"
  head
    title
      =content_for(:title) ? yield(:title) : t('header.title')
    meta http-equiv="Content-type" content="text/html; charset=utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: :all
    = javascript_include_tag 'vendor/modernizr'

  body
    = render 'layouts/top_bar'
    .hide-for-small
      .row.full
        = image_tag 'title.jpg', size: '2000x200'

    #content
      .row
        .large-12.columns
          - if flash[:notice]
            .alert-box.info[data-alert]
              = flash[:notice]
              a.close href='#'= 'x';
          - if flash[:warn]
            .alert-box.warning[data-alert]
              = flash[:warn]
              a.close href='#'= 'x';
          - if flash[:alert]
            .alert-box.warning[data-alert]
              = flash[:alert]
              a.close href='#'= 'x';
      .row
        .large-12.columns
          = yield
    = javascript_include_tag 'application'
    = render 'layouts/footer'

app/views/user_profiles/_address.slim
= f.fields_for :profile_address do |a|
  .row
    .large-6.small-centered.columns
      = error_for_model_and_attribute @user_profile.profile_address, :street_1
      = a.label :street_1
      = a.text_field :street_1
  .row
    .large-6.small-centered.columns
      = error_for_model_and_attribute @user_profile.profile_address, :street_2
      = a.label :street_2
      = a.text_field :street_2
  .row
    .large-6.small-centered.columns
      = error_for_model_and_attribute @user_profile.profile_address, :postal_code
      = a.label :postal_code
      = a.text_field :postal_code
  .row
    .large-6.small-centered.columns
      = error_for_model_and_attribute @user_profile.profile_address, :city
      = a.label :city
      = a.text_field :city

app/views/user_profiles/show.slim
.row
  .large-6.small-centered.columns
    h1= t('.title')
.row
  .large-6.small-centered.columns
    br
    = image_tag gravatar_image_url(@user_profile.user.email), class: 'th [radius]'
    br
    br
    br
= form_for(@user_profile, html: { method: :put }) do |f|
  .row
    .large-6.small-centered.columns
      = error_for_model_and_attribute @user_profile, :name
      = f.label :name
      = f.text_field :name
  .row
    .large-6.small-centered.columns
      br
      br
      h3= t('.address')
      br
  = render 'address', f: f if FeatureToggle.on?(:user_profile_address)
  .row
    .large-6.small-centered.columns
      = f.submit t('update'), class: 'button'

app/views/welcome/features.html.slim
.row.feature
  .large-4.columns.text-center
    h1
      small= t('features.feature_a')
    = image_tag 'feature_a.jpg'
    p
      small= t('features.feature_a_desc')

  .large-4.columns.text-center
    h1
      small= t('features.feature_b')
    = image_tag 'feature_b.jpg'
    p
      small= t('features.feature_b_desc')

  .large-4.columns.text-center
    h1
      small= t('features.feature_c')
    = image_tag 'feature_c.jpg'
    p
      small= t('features.feature_c_desc')

app/views/welcome/index.html.slim
h1= t('header.title')